### ISSUE TITLE
Gestion du signe - avec les fractions

### ISSUE THREAD

**Issue by quark67** [cpierquet/ResolSysteme#1]
La documentation indique (voir par exemple le code commenté de la section 2.2) que la sortie par défaut affiche la fraction avec le signe - sur le numérateur. 

Y a-t-il une raison particulière pour ce choix plutôt bizarre et pas très joli typographiquement (il me semble) ? Quitte à conserver l'option (vu que le package, à la suite de ProfLycee, semble destiné à produire des documents pour un public ayant potentiellement des difficultés avec les maths, ce qui me semble être une raison pour laquelle le signe moins apparaît dans le numérateur), ne serait-il pas plus judicieux d'inverser le sens des commandes étoilées et non étoilées, éventuellement en introduisant une option lors du chargement du package ?

**Comment by cpierquet** [comment]
La raison est simple : au départ la sortie était formatée avec le signe "-" sur le numérateur du fait de l'affichage \frac{num}{denom} ! J'ai rajouté ensuite la commande étoilée pour forcer l'affichage du "-" devant, mais c'est vrai que dans la logique cela devrait être le contraire !!! Solution de facilité quand tu nous tiens...
Si la commande \ibooleanFT existe ça sera très simple d'inverser le comportement, sinon un peu de copier-coller !
Je pense faire la même modification sur ProfLycee, avec la commande jumelle !

Merci pour le retour :-)
