### ISSUE TITLE
How can I solve this system of equations with rational coefficients?

### ISSUE THREAD

**Issue by minhthien2016** [cpierquet/ResolSysteme#2]
```
\documentclass[12pt,a4paper]{article}
\usepackage{systeme}
\usepackage{ResolSysteme}
\begin{document}

La solution de $\systeme{\frac{2}{7}x + \frac{5}{9}y = 13,\frac{73}{37} x - 9y=-11}$ est $\mathcal{S}=%
\left\lbrace \SolutionSysteme[d](2/7,5/9 § 73/37,-9)(13,-11) \right\rbrace$.\\

\end{document}
```

![image](https://github.com/cpierquet/ResolSysteme/assets/55286040/eb06a346-40ed-4d2e-a745-0d9801ed6e6a)

**Comment by cpierquet** [comment]
Hi-
It's maybe a bug with parenthesis...
I need to test ;-)

**Comment by minhthien2016** [comment]
Have you posted the update to Ctan yet?

**Comment by cpierquet** [comment]
Yes, 0.1.7 is uploaded, so in a few days in TeXlive and/or MikTeX.
![image](https://github.com/cpierquet/ResolSysteme/assets/45103962/81b79aed-de79-4400-984e-c3d05761d760)

**Comment by minhthien2016** [comment]
How about this system of equation? 
```
\documentclass[12pt,a4paper]{article}
\usepackage{systeme}
\usepackage{ResolSysteme}
\begin{document}
La solution de $\systeme{\sqrt{3}x + \sqrt{2}y = 1, x - 9y=-5}$ est
	$\mathcal{S}=%
	\left\lbrace \SolutionSysteme[d](sqrt(3),sqrt(2) § 1,-9)(1,-5) \right\rbrace$.\\
\end{document}
```
With Mathematica, I got

![image](https://github.com/cpierquet/ResolSysteme/assets/55286040/d4b213ff-e5b0-4805-93ea-79523e933a8a)

**Comment by cpierquet** [comment]
With square roots it's not working, with python.sympy or not...
