### ISSUE TITLE
How can I draw this graph

### ISSUE THREAD

**Issue by minhthien2016** [cpierquet/ResolSysteme#4]
![image](https://github.com/cpierquet/ResolSysteme/assets/55286040/879acab3-fc71-4463-9472-96fad7c2e4b2)
I know that, the formula of the funtion is 
$sqrt(222.58^2+(2*pi*\x*0.318)^2)/sqrt(222.58^2+(2*pi*\x*0.318-1/(2*pi*\x*8*10^(-2)))^2)$

**Comment by cpierquet** [comment]
Not with `resolsysteme`, but maybe with `tkz-grapheur`.
But the formula don't give the _correct_ curve...

```
\documentclass[margin=5mm]{standalone}
\usepackage{tkz-grapheur}

\begin{document}

\begin{GraphTikz}%
	[x=0.0125cm,y=2cm,Xmin=0,Xmax=520,Xgrid=40,Xgrids=40,
	Ymin=0,Ymax=1.5,Ygrid=0.25,Ygrids=0.25]
	\DrawAxisGrids[Grads=false,Enlarge=2.5mm,Font=\footnotesize]%
		{auto}
		{auto}
	\DrawCurve[Color=red,Start=1]{sqrt(222.58^2+(2*pi*x*0.318)^2)/sqrt(222.58^2+(2*pi*x*0.318-1/(2*pi*x*810^(-2)))^2)}
\end{GraphTikz}

\end{document}
```

![image](https://github.com/cpierquet/ResolSysteme/assets/45103962/7a200383-1acf-4227-a042-20e5fe1d85f0)

![image](https://github.com/cpierquet/ResolSysteme/assets/45103962/3107dae3-9c3a-46b3-b82e-d03a1e744d5c)

**Comment by minhthien2016** [comment]
Thank you very much.
